###
POST http://localhost/web/salones_belaircdmx_com/api/events/ HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VycyI6MSwiZXhwIjoxNzQ4MTMxODQ2fQ.zEhgBTPlv4jn7esLqQUrvruVLchy_eFmBGwJZLUe_Y8

{
    "action": "select",
    "table": "users",
    "options": {
    }
}